mode: http

db:
    path: /var/lib/melodeon/store.db

logging:
    dir: /var/log/melodeon
    level: 4

rooms:
    bucket_name: rooms

sessions:
    bucket_name: sessions
    signing_key: '1DrJ5fMTc0U//jqsbOizio1BxG4GBDAIv1qYbdMIx34fxij1/Ww++tk8Ct8svTR5V6uZMh1Rm+z0CxrJEKEmuw=='
    encrypt_key: 'defAA8mBKcG1OQTIlFcosBtTLNATEZOdrPzldXAiTdc='
    cookie:
        path: /
        max_age: 86400
        same_site: none

spotify:
    client_id: 'bc41068f439544ea8bdf80bee8088c62'
    client_secret: '217af814a63c47b4ad9a1b3a88b795cc'
    redirect_uri: 'https://melodeon.bdreece.dev/authorize'

web:
    static_dir: /usr/share/melodeon/static
    assets_dir: /usr/share/melodeon/assets
    template_dir: /usr/share/melodeon/templates
